#NUMPY


In [2]:
import numpy as np

arr = np.array ([1,2,3,4,5])
print(arr)  

[1 2 3 4 5]


In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,45,6)

array([ 1,  7, 13, 19, 25, 31, 37, 43])

In [7]:
np.zeros(10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

##create an arrays of zeros with 2 rows and 10 colomn

In [9]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [10]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
import numpy as np


In [13]:
np.random.rand(3,2)

array([[0.38400853, 0.38252091],
       [0.46908039, 0.23336092],
       [0.46503702, 0.12993949]])

In [14]:
np.random.randn(3,2)

array([[ 0.8342924 ,  1.62635108],
       [ 1.28237512, -0.39732771],
       [-1.06745294,  0.2559714 ]])

In [15]:
np.random.randint(34,100)

80

In [16]:
np.random.randint(1,2)

1

In [17]:
np.random.randint(20,56,100)

array([44, 39, 35, 30, 54, 38, 26, 43, 37, 49, 43, 50, 47, 23, 29, 50, 33,
       30, 28, 53, 23, 42, 43, 40, 38, 43, 44, 39, 54, 48, 47, 32, 52, 33,
       40, 37, 43, 25, 27, 52, 50, 39, 44, 31, 55, 43, 30, 24, 45, 22, 25,
       31, 37, 52, 31, 26, 51, 34, 52, 21, 40, 53, 21, 54, 23, 52, 20, 53,
       46, 28, 20, 39, 31, 31, 49, 44, 36, 30, 54, 32, 38, 51, 55, 46, 28,
       32, 49, 20, 24, 28, 45, 47, 26, 23, 47, 34, 30, 22, 55, 23])

In [18]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
rand_array=np.random.randint(0,100,20)
rand_array

array([33, 37,  9, 44, 27, 75, 24, 20, 20, 41, 86, 60, 91, 35, 91, 11,  0,
       38, 10, 64])

In [20]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [21]:
rand_array.min()

0

In [22]:
rand_array.argmin()

16

In [23]:
rand_array.max()

91

In [24]:
rand_array.argmax()

12

In [26]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a=np.random.rand(2,3)
a

array([[0.9551694 , 0.53308813, 0.47950727],
       [0.33590188, 0.77441626, 0.9459965 ]])

In [29]:
a.T

array([[0.9551694 , 0.33590188],
       [0.53308813, 0.77441626],
       [0.47950727, 0.9459965 ]])

In [30]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
sample_array[-3]

18

In [33]:
sample_array[3:7]

array([13, 14, 15, 16])

In [34]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [36]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [38]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [39]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [41]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

two dimentional array

In [42]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [43]:
sample_matrix[0][2]

1

In [44]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [45]:
sample_matrix[2]

array([56, 76, 24,  7])

In [46]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

selection techniques

In [48]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [49]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [50]:
np.exp(sample_array)    #expnential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [51]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [52]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [53]:
np.max(sample_array)

19

In [54]:
np.min(sample_array)

1

In [55]:
np.argmax(sample_array)

18

In [56]:
np.argmin(sample_array)

0

In [57]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [58]:
np.std(sample_array)

5.477225575051661

In [59]:
np.var(sample_array)

30.0

In [60]:
np.mean(sample_array)

10.0

In [61]:
array=np.random.randn(3,4)
array

array([[ 0.66207697,  0.3138505 ,  0.17580249,  0.17710222],
       [-0.2536156 , -0.65640202, -0.65813955, -1.42839564],
       [ 1.33768612,  1.35096414,  0.8991432 ,  1.36354012]])

In [63]:
np.round(array,decimals=4)

array([[ 0.6621,  0.3139,  0.1758,  0.1771],
       [-0.2536, -0.6564, -0.6581, -1.4284],
       [ 1.3377,  1.351 ,  0.8991,  1.3635]])

In [64]:
sport=np.array(['golf','cricket','football','fball','cricket'])
np.unique(sport)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')